config/routes.rb
Rails.application.routes.draw do
  resources :snotes
  resources :notes do
    resources :snotes, only: [:create]
  end
  # get 'welcome/index'
  # root 'welcome#index'

  # need both constraints to work
  constraints Clearance::Constraints::SignedIn.new do
    root to: "welcome#index", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "welcome#index"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # root "clearance/users#new"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	has_many :snotes
end

app/models/snote.rb
class Snote < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :notes
  has_many :snotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
  before_filter :set_cache_buster

  #prevent back action after sign_out
  def set_cache_buster
  	response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
  	response.headers["Pragma"] = "no-cache"
  	response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/clearance/sessions_controller.rb
class Clearance::SessionsController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:new]
    skip_before_action :require_login,
      only: [:create, :new, :destroy],
      raise: false
    skip_before_action :authorize,
      only: [:create, :new, :destroy],
      raise: false
  else
    before_filter :redirect_signed_in_users, only: [:new]
    skip_before_filter :require_login,
      only: [:create, :new, :destroy],
      raise: false
    skip_before_filter :authorize,
      only: [:create, :new, :destroy],
      raise: false
  end

  def create
    @user = authenticate(params)

    sign_in(@user) do |status|
      if status.success?
        redirect_back_or url_after_create
      else
        flash.now.notice = status.failure_message
        render template: "sessions/new", status: :unauthorized
      end
    end
  end

  def destroy
    sign_out
    redirect_to url_after_destroy
  end

  def new
    render template: "sessions/new"
  end

  private

  def redirect_signed_in_users
    if signed_in?
      redirect_to url_for_signed_in_users
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def url_after_destroy
    # changed the line below - yoohoo newbie way. All jumbled up
    root_url
  end

  def url_for_signed_in_users
    url_after_create
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_filter :validate_user

  def validate_user
    if current_user == nil
      redirect_to root_url
    end
  end

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where(user_id: current_user)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note.lastseen = Time.now
    @note.save
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/controllers/snotes_controller.rb
class SnotesController < ApplicationController
  before_action :set_snote, only: [:show, :edit, :update, :destroy]

  # GET /snotes
  # GET /snotes.json
  def index
    @snotes = Snote.all
  end

  # GET /snotes/1
  # GET /snotes/1.json
  def show
  end

  # GET /snotes/new
  def new
    @snote = Snote.new
  end

  # GET /snotes/1/edit
  def edit
  end

  # POST /snotes
  # POST /snotes.json
  def create
    @snote = Snote.new(snote_params)
    @snote.note_id = params["note_id"]
    @snote.user_id = current_user.id

    respond_to do |format|
      if @snote.save
        format.html { redirect_to @snote, notice: 'Snote was successfully created.' }
        format.json { render :show, status: :created, location: @snote }
      else
        format.html { render :new }
        format.json { render json: @snote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snotes/1
  # PATCH/PUT /snotes/1.json
  def update
    respond_to do |format|
      if @snote.update(snote_params)
        format.html { redirect_to @snote, notice: 'Snote was successfully updated.' }
        format.json { render :show, status: :ok, location: @snote }
      else
        format.html { render :edit }
        format.json { render json: @snote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snotes/1
  # DELETE /snotes/1.json
  def destroy
    @snote.destroy
    respond_to do |format|
      format.html { redirect_to snotes_url, notice: 'Snote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snote
      @snote = Snote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snote_params
      params.require(:snote).permit(:title, :answer, :pnote, :freq, :user_id, :note_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if signed_in?
  	@notes = Note.all
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/snotes_helper.rb
module SnotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mrdr</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge/>
    
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= current_user.email %>'s Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.content %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

<br>
<br>
<% if signed_in? %>
  <%= current_user.email %>
  <%= button_to "Sign out", sign_out_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", sign_in_path %>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/">MrDr</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><select id="voiceselection" style="color: black;"></select></a></li>
        <li><a href="#snote">New Snote</a></li>
        <li><a href="#logout">Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<p id="notice"><%= notice %></p>

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-folder-open logo"></span>
    </div>
    <div class="col-sm-8">
      <h2><strong>Title: </strong> <%= @note.title %></h2>
      <br>
      <h4>CONTENT: <%= @note.content %></h4>
      <%= link_to 'Edit', edit_note_path(@note), class: "btn btn-lg" %>
      <% if @note.snotes.any? %>
      <% x = 1 %>
      <% @note.snotes.each do |snote|%>
        <button type="button" class="col-md-8 col-sm-8 btn btn-block" style="white-space: normal;" data-toggle="collapse" data-target="#demo<%= x %>"> <%= snote.title %>
        </button>
        <div id="demo<%= x %>" class="col-md-12 col-sm-12 collapse">
        <p><%= simple_format(snote.answer) %></p>
        <p style="display: none"><%= snote.answer %></p>
        <input class="btn"
          onclick="responsiveVoice.speak($(this).prev().html(), $('#voiceselection').val());"
          type="button"
          value="Play"/>
        <input class="btn"
          onclick="responsiveVoice.pause();"
          type="button"
          value="Pause"/>
        <input class="btn"
          onclick="responsiveVoice.resume();"
          type="button"
          value="Resume"/>
        <input class="btn"
          onclick="responsiveVoice.cancel();"
          type="button"
          value="Stop"/>
          <%= link_to 'Edit', edit_snote_path(snote) %>
          <button type="button" class="col-md-8 col-sm-8 btn pull-left" style="display: inline-block;" data-toggle="collapse" data-target="#demos<%= x %>"> Reminder </button>
          <div id="demos<%= x %>" class="col-md-8 col-sm-8 collapse pull-left">
          <p><%= snote.pnote %></p>
          </div>
        </div>
        <% x += 1 %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

  <div id="snote" class="container-fluid bg-grey">
    <h2 class="text-left">New Snote</h2>
    <div class="row">
      <div class="col-sm-7">
        <div class="row">    
            <% @snote = Snote.new %>
<%= render 'snotes/form', snote: @snote %>
        </div>
      </div>
    </div>
  </div>



<footer id="logout" class="container-fluid text-center">
  <%= link_to "", sign_out_path, class: 'glyphicon glyphicon-log-out',method: :delete %>
  <p>Log Out. Go get some rest.</p>
</footer>

<script src="https://code.responsivevoice.org/responsivevoice.js"></script>
<script>
  //Populate voice selection dropdown
    var voicelist = responsiveVoice.getVoices();
    var vselect = $("#voiceselection");
    $.each(voicelist, function() {
    vselect.append($("<option />").val(this.name).text(this.name));
  });

    $(document).ready(function(){
      $("button").click(function(){
          x = $(this).children('span').html();
          x = parseInt(x) + 1;
          $(this).children('span').html(x);
      });
    });

    
</script>

app/views/snotes/_form.html.erb
<%= form_for [@note, snote], html: { class: "form-group"} do |f| %>
  <% if snote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(snote.errors.count, "error") %> prohibited this snote from being saved:</h2>

      <ul>
      <% snote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group col-sm-8">
    <%= f.text_field :title, type: 'text', class: "form-control", placeholder: 'Title'%>
  </div>
  <br>

  <div class="field form-group col-sm-8">
    <%= f.text_area :answer, type: 'text', class: "form-control", placeholder: 'Answer', id: "comment" %>
  </div>

  <div class="field form-group col-sm-8">
    <%= f.text_area :pnote, type: 'text', class: "form-control", placeholder: 'Pnote' %>
  </div>

  <div class="actions form-group col-sm-6">
    <%= f.submit type: 'submit', class: 'btn btn-default'%>
  </div>
<% end %>

app/views/snotes/edit.html.erb
<h1>Editing Snote</h1>

<%= render 'form', snote: @snote %>

<%= link_to 'Show', @snote %> |
<%= link_to 'Back', snotes_path %>

app/views/snotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Snotes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Answer</th>
      <th>Pnote</th>
      <th>Freq</th>
      <th>User</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snotes.each do |snote| %>
      <tr>
        <td><%= snote.title %></td>
        <td><%= snote.answer %></td>
        <td><%= snote.pnote %></td>
        <td><%= snote.freq %></td>
        <td><%= snote.user %></td>
        <td><%= snote.note %></td>
        <td><%= link_to 'Show', snote %></td>
        <td><%= link_to 'Edit', edit_snote_path(snote) %></td>
        <td><%= link_to 'Destroy', snote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snote', new_snote_path %>

app/views/snotes/new.html.erb
<h1>New Snote</h1>

<%= render 'form', snote: @snote %>

<%= link_to 'Back', snotes_path %>

app/views/snotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @snote.title %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @snote.answer %>
</p>

<p>
  <strong>Pnote:</strong>
  <%= @snote.pnote %>
</p>

<p>
  <strong>Freq:</strong>
  <%= @snote.freq %>
</p>

<p>
  <strong>User:</strong>
  <%= @snote.user %>
</p>

<p>
  <strong>Note:</strong>
  <%= @snote.note %>
</p>

<%= link_to 'Bank to Note', @snote.note, class: "btn btn-lg" %> |
<%= link_to 'Edit', edit_snote_path(@snote) %> |
<%= link_to 'Back', snotes_path %>

app/views/welcome/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#myPage">MrDr</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <li><a href="#notes">NOTES</a></li>
        <li><a href="#signout">SIGN OUT</a></li>
      <% else %>
        <li><a href="#signin">SIGN IN</a></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

<% if signed_in? %>
  <div id="notes" class="container-fluid">
    <div class="text-center">
      <h2>Notes</h2>
      <h4>Listen UP!!</h4>
    </div>
    <div class="row slideanim">
      <% @notes.order('lastseen ASC').each do |note| %>
      <div class="col-sm-4 col-xs-12">
        <div class="panel panel-default text-center">
          <div class="panel-heading">
            <h1><%= note.title %></h1>
          </div>
          <div class="panel-body" style="height: 200px;">
            <p><%= note.content %></p>
          </div>
          <div class="panel-footer">
            <h4><%= time_ago_in_words(note.lastseen) %></h4>
            <%= link_to 'Show', note, class: "btn btn-lg"%>
          </div>
        </div>      
      </div>
      <% end %>
    </div>
  </div>

  <%= link_to 'New Note', new_note_path %>

  <footer id="signout" class="container-fluid text-center">
    <%= link_to "", sign_out_path, class: 'glyphicon glyphicon-log-out',method: :delete %>
    <p><%= current_user.email %> <br>
    Log Out. Go get some rest.</p>
  </footer>
<% else %>

<!-- Container (Contact Section) -->
<div id="signin" class="container-fluid bg-grey">
  <h2 class="text-center">SIGN IN</h2>
  <div class="row">
    <div class="col-sm-5">
      <p>Contact us and we'll get back to you within 24 hours.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Chicago, US</p>
      <p><span class="glyphicon glyphicon-phone"></span> +00 1515151515</p>
      <p><span class="glyphicon glyphicon-envelope"></span> myemail@something.com</p>
    </div>
    <div class="col-sm-7 slideanim">
      <div class="row">
        <div id="clearance" class="sign-in">
            <h2><%= t(".title") %></h2>

            <%= render partial: '/sessions/form' %>

          </div>
      </div>
      
      <textarea class="form-control" id="comments" name="comments" placeholder="Play me out loud!!" rows="5"></textarea>
      <select id="voiceselection"></select>
      <br>
      <div class="row">
        <div class="col-sm-12 form-group">
          <input class="btn btn-default pull-right" onclick="responsiveVoice.speak($('#comments').val(), $('#voiceselection').val());"
          type="button" value= "Play" />
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<script src="https://code.responsivevoice.org/responsivevoice.js"></script>
<script>

$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
  
  $(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;

      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
        }
    });
  });

  //Populate voice selection dropdown
        var voicelist = responsiveVoice.getVoices();
        var vselect = $("#voiceselection");
        $.each(voicelist, function() {
                vselect.append($("<option />").val(this.name).text(this.name));
        });
})
</script>